import type { CardData } from "@/features/cards/types"

export const DEMO_CARDS: CardData[] = [
	{
		id: "demo-1",
		title: "Rickroll",
		imageUrl: null,
		description: "Never gonna give you up",
		flavorText: "You know the rules, and so do I.",
		stats: { atk: 99, def: 85, spd: 72, hp: 90 },
		rarity: "legendary",
		elementType: "blitz",
		isHolographic: true,
		superlative: null,
	},
	{
		id: "demo-2",
		title: "Doge",
		imageUrl: null,
		description: "Much wow. Very card.",
		flavorText: "Such collection. Many trade. Wow.",
		stats: { atk: 45, def: 60, spd: 80, hp: 55 },
		rarity: "epic",
		elementType: "swift",
		isHolographic: false,
		superlative: null,
	},
	{
		id: "demo-3",
		title: "Distracted Boyfriend",
		imageUrl: null,
		description: "Looking at that new card set",
		flavorText: "His collection will never be complete.",
		stats: { atk: 30, def: 25, spd: 50, hp: 40 },
		rarity: "rare",
		elementType: "fortress",
		isHolographic: false,
		superlative: null,
	},
	{
		id: "demo-4",
		title: "This Is Fine Dog",
		imageUrl: null,
		description: "Everything is fine",
		flavorText: "Opens 50 packs. No legendary. This is fine.",
		stats: { atk: 15, def: 90, spd: 10, hp: 70 },
		rarity: "uncommon",
		elementType: "fortress",
		isHolographic: false,
		superlative: null,
	},
	{
		id: "demo-5",
		title: "Stonks",
		imageUrl: null,
		description: "Trading cards go up",
		flavorText: "Diversified portfolio of rare holos.",
		stats: { atk: 20, def: 20, spd: 20, hp: 20 },
		rarity: "common",
		elementType: "blitz",
		isHolographic: false,
		superlative: null,
	},
]
